version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    time: "20:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: ray/di
    versions:
    - 2.11.2
  - dependency-name: laminas/laminas-httphandlerrunner
    versions:
    - 1.3.0
  - dependency-name: phpmd/phpmd
    versions:
    - 2.9.0
